### ISSUE TITLE
 display compatibility,Additional message text and short_message_id in the message templates are not properly formed triples in cedar

### ISSUE THREAD

**Issue by icejag** [Display-Lab/knowledge-base#187] opened 2023-11-28 18:01 UTC
The rdflib package of python converts the knowledge graph triples to tuples. Thie rdflib package is used in our PFP-pipeline software. Apparently the rdflib package is not able to convert the Display compatibility,Additional message text and short message id to tuple ,because of missing subject.
```
Example tuples generated by rdflib for a message_template:
https://repo.metadatacenter.org/template-instances/96a74b9d-8781-4b04-bf00-d999830237bc http://schema.org/nameIn Top 25%
https://repo.metadatacenter.org/template-instances/96a74b9d-8781-4b04-bf00-d999830237bc http://purl.org/pav/lastUpdatedOn2023-10-31T15:28:11-07:00
https://repo.metadatacenter.org/template-instances/96a74b9d-8781-4b04-bf00-d999830237bc https://schema.metadatacenter.org/properties/26450fa6-bb2c-4126-8229-79efda7f863aIn Top 25%
http://purl.obolibrary.org/obo/PSDO_0000117 http://www.w3.org/2000/01/rdf-schema#labelpositive performance gap set
http://purl.obolibrary.org/obo/PSDO_0000045 http://www.w3.org/2000/01/rdf-schema#labelsocial comparator element
https://repo.metadatacenter.org/template-instances/96a74b9d-8781-4b04-bf00-d999830237bc http://purl.obolibrary.org/obo/IAO_0000136http://purl.obolibrary.org/obo/PSDO_0000128
https://repo.metadatacenter.org/template-instances/96a74b9d-8781-4b04-bf00-d999830237bc http://purl.org/pav/createdOn2023-06-28T12:28:07-07:00
https://repo.metadatacenter.org/template-instances/96a74b9d-8781-4b04-bf00-d999830237b chttp://purl.obolibrary.org/obo/IAO_0000136http://purl.obolibrary.org/obo/PSDO_0000117
https://repo.metadatacenter.org/template-instances/96a74b9d-8781-4b04-bf00-d999830237bc http://schema.org/descriptionspecification for a possible precision feedback message
https://repo.metadatacenter.org/template-instances/96a74b9d-8781-4b04-bf00-d999830237bc http://purl.obolibrary.org/obo/IAO_0000136 http://purl.obolibrary.org/obo/PSDO_0000045
https://repo.metadatacenter.org/template-instances/96a74b9d-8781-4b04-bf00-d999830237bc http://schema.org/isBasedOn https://repo.metadatacenter.org/templates/707d3573-8ac9-4e2c-b53b-2026a795308c
https://repo.metadatacenter.org/template-instances/96a74b9d-8781-4b04-bf00-d999830237bc http://purl.org/pav/createdBy https://metadatacenter.org/users/da882240-ad9e-42ea-a48b-215e54161ad3
https://repo.metadatacenter.org/template-instances/96a74b9d-8781-4b04-bf00-d999830237bc http://purl.org/pav/derivedFrom https://repo.metadatacenter.org/template-instances/b7685a3f-5b7b-4291-b194-92e410c99e8d
http://purl.obolibrary.org/obo/PSDO_0000128 http://www.w3.org/2000/01/rdf-schema#labelpeer 75th percentile benchmark
https://repo.metadatacenter.org/template-instances/96a74b9d-8781-4b04-bf00-d999830237bc http://open-services.net/ns/core#modifiedBy https://metadatacenter.org/users/da882240-ad9e-42ea-a48b-215e54161ad3
https://repo.metadatacenter.org/template-instances/96a74b9d-8781-4b04-bf00-d999830237bc https://schema.metadatacenter.org/properties/6b9dfdf9-9c8a-4d85-8684-a24bee4b85a8 You are in the top 25% of providers for the measure [measure name]. Your performance was [recipient performance level], above the top 25% peer benchmark, which was [comparator performance level] this month.
https://repo.metadatacenter.org/template-instances/96a74b9d-8781-4b04-bf00-d999830237bc http://www.w3.org/1999/02/22-rdf-syntax-ns#type http://data.bioontology.org/ontologies/PSDO/classes/http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPSDO_0000002
```

Suggestion/fix: Move the Display compatibility, addition message text and short message id near message name and message text. In that case it will have same subject as message text and message name and it is easily converted to triples by rdflib package.

**Comment by zachll** [comment] 2023-12-05 20:45
Duplicate of this issue: #188

**Closed by zachll** 2023-12-05 20:45 UTC
Labels: bug
